name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  server:
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v2.2.0
      with:
        fetch-depth: 0

    - name: Setup Babashka
      uses: turtlequeue/setup-babashka@v1.3.0
      with:
        babashka-version: 0.7.0

    - name: Publish assets
      run: bb publish
